[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "deep-translator>=1.11.4",
    "edge-tts>=7.2.8",
    "fastapi>=0.141.1",
    "openai-whisper>=20250625",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
]
